// Lista completa de comunas chilenas organizadas por región
export const COMUNAS_CHILE = [
  // Región de Arica y Parinacota
  { nombre: 'Arica', region: 'Arica y Parinacota', codigo: '15101' },
  { nombre: 'Camarones', region: 'Arica y Parinacota', codigo: '15102' },
  { nombre: 'General Lagos', region: 'Arica y Parinacota', codigo: '15202' },
  { nombre: 'Putre', region: 'Arica y Parinacota', codigo: '15201' },
  
  // Región de Tarapacá
  { nombre: 'Alto Hospicio', region: 'Tarapacá', codigo: '01107' },
  { nombre: 'Camiña', region: 'Tarapacá', codigo: '01402' },
  { nombre: 'Colchane', region: 'Tarapacá', codigo: '01403' },
  { nombre: 'Huara', region: 'Tarapacá', codigo: '01404' },
  { nombre: 'Iquique', region: 'Tarapacá', codigo: '01101' },
  { nombre: 'Pica', region: 'Tarapacá', codigo: '01405' },
  { nombre: 'Pozo Almonte', region: 'Tarapacá', codigo: '01401' },
  
  // Región de Antofagasta
  { nombre: 'Antofagasta', region: 'Antofagasta', codigo: '02101' },
  { nombre: 'Calama', region: 'Antofagasta', codigo: '02201' },
  { nombre: 'María Elena', region: 'Antofagasta', codigo: '02104' },
  { nombre: 'Mejillones', region: 'Antofagasta', codigo: '02102' },
  { nombre: 'Ollagüe', region: 'Antofagasta', codigo: '02202' },
  { nombre: 'San Pedro de Atacama', region: 'Antofagasta', codigo: '02203' },
  { nombre: 'Sierra Gorda', region: 'Antofagasta', codigo: '02103' },
  { nombre: 'Taltal', region: 'Antofagasta', codigo: '02301' },
  { nombre: 'Tocopilla', region: 'Antofagasta', codigo: '02302' },
  
  // Región de Atacama
  { nombre: 'Alto del Carmen', region: 'Atacama', codigo: '03302' },
  { nombre: 'Caldera', region: 'Atacama', codigo: '03102' },
  { nombre: 'Chañaral', region: 'Atacama', codigo: '03201' },
  { nombre: 'Copiapó', region: 'Atacama', codigo: '03101' },
  { nombre: 'Diego de Almagro', region: 'Atacama', codigo: '03202' },
  { nombre: 'Freirina', region: 'Atacama', codigo: '03301' },
  { nombre: 'Huasco', region: 'Atacama', codigo: '03304' },
  { nombre: 'Tierra Amarilla', region: 'Atacama', codigo: '03103' },
  { nombre: 'Vallenar', region: 'Atacama', codigo: '03303' },
  
  // Región de Coquimbo
  { nombre: 'Andacollo', region: 'Coquimbo', codigo: '04103' },
  { nombre: 'Canela', region: 'Coquimbo', codigo: '04202' },
  { nombre: 'Combarbalá', region: 'Coquimbo', codigo: '04302' },
  { nombre: 'Coquimbo', region: 'Coquimbo', codigo: '04102' },
  { nombre: 'Illapel', region: 'Coquimbo', codigo: '04203' },
  { nombre: 'La Higuera', region: 'Coquimbo', codigo: '04104' },
  { nombre: 'La Serena', region: 'Coquimbo', codigo: '04101' },
  { nombre: 'Los Vilos', region: 'Coquimbo', codigo: '04204' },
  { nombre: 'Monte Patria', region: 'Coquimbo', codigo: '04303' },
  { nombre: 'Ovalle', region: 'Coquimbo', codigo: '04301' },
  { nombre: 'Paihuano', region: 'Coquimbo', codigo: '04105' },
  { nombre: 'Punitaqui', region: 'Coquimbo', codigo: '04304' },
  { nombre: 'Río Hurtado', region: 'Coquimbo', codigo: '04305' },
  { nombre: 'Salamanca', region: 'Coquimbo', codigo: '04201' },
  { nombre: 'Vicuña', region: 'Coquimbo', codigo: '04106' },
  
  // Región de Valparaíso
  { nombre: 'Algarrobo', region: 'Valparaíso', codigo: '05602' },
  { nombre: 'Cabildo', region: 'Valparaíso', codigo: '05402' },
  { nombre: 'Calera', region: 'Valparaíso', codigo: '05502' },
  { nombre: 'Calle Larga', region: 'Valparaíso', codigo: '05602' },
  { nombre: 'Cartagena', region: 'Valparaíso', codigo: '05603' },
  { nombre: 'Casablanca', region: 'Valparaíso', codigo: '05102' },
  { nombre: 'Catemu', region: 'Valparaíso', codigo: '05503' },
  { nombre: 'Concón', region: 'Valparaíso', codigo: '05103' },
  { nombre: 'El Quisco', region: 'Valparaíso', codigo: '05604' },
  { nombre: 'El Tabo', region: 'Valparaíso', codigo: '05605' },
  { nombre: 'Hijuelas', region: 'Valparaíso', codigo: '05504' },
  { nombre: 'Isla de Pascua', region: 'Valparaíso', codigo: '05201' },
  { nombre: 'Juan Fernández', region: 'Valparaíso', codigo: '05104' },
  { nombre: 'La Calera', region: 'Valparaíso', codigo: '05502' },
  { nombre: 'La Cruz', region: 'Valparaíso', codigo: '05505' },
  { nombre: 'La Ligua', region: 'Valparaíso', codigo: '05401' },
  { nombre: 'Limache', region: 'Valparaíso', codigo: '05506' },
  { nombre: 'Llaillay', region: 'Valparaíso', codigo: '05507' },
  { nombre: 'Los Andes', region: 'Valparaíso', codigo: '05301' },
  { nombre: 'Nogales', region: 'Valparaíso', codigo: '05508' },
  { nombre: 'Olmué', region: 'Valparaíso', codigo: '05509' },
  { nombre: 'Panquehue', region: 'Valparaíso', codigo: '05510' },
  { nombre: 'Papudo', region: 'Valparaíso', codigo: '05403' },
  { nombre: 'Petorca', region: 'Valparaíso', codigo: '05404' },
  { nombre: 'Puchuncaví', region: 'Valparaíso', codigo: '05105' },
  { nombre: 'Putaendo', region: 'Valparaíso', codigo: '05511' },
  { nombre: 'Quillota', region: 'Valparaíso', codigo: '05501' },
  { nombre: 'Quilpué', region: 'Valparaíso', codigo: '05106' },
  { nombre: 'Quintero', region: 'Valparaíso', codigo: '05107' },
  { nombre: 'Rinconada', region: 'Valparaíso', codigo: '05302' },
  { nombre: 'San Antonio', region: 'Valparaíso', codigo: '05601' },
  { nombre: 'San Esteban', region: 'Valparaíso', codigo: '05303' },
  { nombre: 'San Felipe', region: 'Valparaíso', codigo: '05512' },
  { nombre: 'Santa María', region: 'Valparaíso', codigo: '05513' },
  { nombre: 'Santo Domingo', region: 'Valparaíso', codigo: '05606' },
  { nombre: 'Valparaíso', region: 'Valparaíso', codigo: '05101' },
  { nombre: 'Villa Alemana', region: 'Valparaíso', codigo: '05109' },
  { nombre: 'Viña del Mar', region: 'Valparaíso', codigo: '05109' },
  { nombre: 'Zapallar', region: 'Valparaíso', codigo: '05405' },
  
  // Región Metropolitana
  { nombre: 'Alhué', region: 'Metropolitana', codigo: '13502' },
  { nombre: 'Buin', region: 'Metropolitana', codigo: '13402' },
  { nombre: 'Calera de Tango', region: 'Metropolitana', codigo: '13403' },
  { nombre: 'Cerrillos', region: 'Metropolitana', codigo: '13102' },
  { nombre: 'Cerro Navia', region: 'Metropolitana', codigo: '13103' },
  { nombre: 'Colina', region: 'Metropolitana', codigo: '13301' },
  { nombre: 'Conchalí', region: 'Metropolitana', codigo: '13104' },
  { nombre: 'Curacaví', region: 'Metropolitana', codigo: '13503' },
  { nombre: 'El Bosque', region: 'Metropolitana', codigo: '13105' },
  { nombre: 'El Monte', region: 'Metropolitana', codigo: '13504' },
  { nombre: 'Estación Central', region: 'Metropolitana', codigo: '13106' },
  { nombre: 'Huechuraba', region: 'Metropolitana', codigo: '13107' },
  { nombre: 'Independencia', region: 'Metropolitana', codigo: '13108' },
  { nombre: 'Isla de Maipo', region: 'Metropolitana', codigo: '13505' },
  { nombre: 'La Cisterna', region: 'Metropolitana', codigo: '13109' },
  { nombre: 'La Florida', region: 'Metropolitana', codigo: '13110' },
  { nombre: 'La Granja', region: 'Metropolitana', codigo: '13111' },
  { nombre: 'La Pintana', region: 'Metropolitana', codigo: '13112' },
  { nombre: 'La Reina', region: 'Metropolitana', codigo: '13113' },
  { nombre: 'Lampa', region: 'Metropolitana', codigo: '13302' },
  { nombre: 'Las Condes', region: 'Metropolitana', codigo: '13114' },
  { nombre: 'Lo Barnechea', region: 'Metropolitana', codigo: '13115' },
  { nombre: 'Lo Espejo', region: 'Metropolitana', codigo: '13116' },
  { nombre: 'Lo Prado', region: 'Metropolitana', codigo: '13117' },
  { nombre: 'Macul', region: 'Metropolitana', codigo: '13118' },
  { nombre: 'Maipú', region: 'Metropolitana', codigo: '13119' },
  { nombre: 'María Pinto', region: 'Metropolitana', codigo: '13506' },
  { nombre: 'Melipilla', region: 'Metropolitana', codigo: '13501' },
  { nombre: 'Ñuñoa', region: 'Metropolitana', codigo: '13120' },
  { nombre: 'Padre Hurtado', region: 'Metropolitana', codigo: '13604' },
  { nombre: 'Paine', region: 'Metropolitana', codigo: '13404' },
  { nombre: 'Pedro Aguirre Cerda', region: 'Metropolitana', codigo: '13121' },
  { nombre: 'Peñaflor', region: 'Metropolitana', codigo: '13605' },
  { nombre: 'Peñalolén', region: 'Metropolitana', codigo: '13122' },
  { nombre: 'Pirque', region: 'Metropolitana', codigo: '13202' },
  { nombre: 'Providencia', region: 'Metropolitana', codigo: '13123' },
  { nombre: 'Pudahuel', region: 'Metropolitana', codigo: '13124' },
  { nombre: 'Puente Alto', region: 'Metropolitana', codigo: '13201' },
  { nombre: 'Quilicura', region: 'Metropolitana', codigo: '13125' },
  { nombre: 'Quinta Normal', region: 'Metropolitana', codigo: '13126' },
  { nombre: 'Recoleta', region: 'Metropolitana', codigo: '13127' },
  { nombre: 'Renca', region: 'Metropolitana', codigo: '13128' },
  { nombre: 'San Bernardo', region: 'Metropolitana', codigo: '13401' },
  { nombre: 'San Joaquín', region: 'Metropolitana', codigo: '13129' },
  { nombre: 'San José de Maipo', region: 'Metropolitana', codigo: '13203' },
  { nombre: 'San Miguel', region: 'Metropolitana', codigo: '13130' },
  { nombre: 'San Pedro', region: 'Metropolitana', codigo: '13507' },
  { nombre: 'San Ramón', region: 'Metropolitana', codigo: '13131' },
  { nombre: 'Santiago', region: 'Metropolitana', codigo: '13101' },
  { nombre: 'Talagante', region: 'Metropolitana', codigo: '13601' },
  { nombre: 'Tiltil', region: 'Metropolitana', codigo: '13303' },
  { nombre: 'Vitacura', region: 'Metropolitana', codigo: '13132' },
  
  // Región del Libertador General Bernardo O'Higgins
  { nombre: 'Chépica', region: "O'Higgins", codigo: '06302' },
  { nombre: 'Chimbarongo', region: "O'Higgins", codigo: '06303' },
  { nombre: 'Codegua', region: "O'Higgins", codigo: '06102' },
  { nombre: 'Coinco', region: "O'Higgins", codigo: '06103' },
  { nombre: 'Coltauco', region: "O'Higgins", codigo: '06104' },
  { nombre: 'Doñihue', region: "O'Higgins", codigo: '06105' },
  { nombre: 'Graneros', region: "O'Higgins", codigo: '06106' },
  { nombre: 'La Estrella', region: "O'Higgins", codigo: '06202' },
  { nombre: 'Las Cabras', region: "O'Higgins", codigo: '06107' },
  { nombre: 'Litueche', region: "O'Higgins", codigo: '06203' },
  { nombre: 'Lolol', region: "O'Higgins", codigo: '06304' },
  { nombre: 'Machalí', region: "O'Higgins", codigo: '06108' },
  { nombre: 'Malloa', region: "O'Higgins", codigo: '06109' },
  { nombre: 'Marchigüe', region: "O'Higgins", codigo: '06204' },
  { nombre: 'Mostazal', region: "O'Higgins", codigo: '06110' },
  { nombre: 'Nancagua', region: "O'Higgins", codigo: '06305' },
  { nombre: 'Navidad', region: "O'Higgins", codigo: '06205' },
  { nombre: 'Olivar', region: "O'Higgins", codigo: '06111' },
  { nombre: 'Palmilla', region: "O'Higgins", codigo: '06306' },
  { nombre: 'Paredones', region: "O'Higgins", codigo: '06206' },
  { nombre: 'Peralillo', region: "O'Higgins", codigo: '06307' },
  { nombre: 'Peumo', region: "O'Higgins", codigo: '06112' },
  { nombre: 'Pichidegua', region: "O'Higgins", codigo: '06113' },
  { nombre: 'Pichilemu', region: "O'Higgins", codigo: '06201' },
  { nombre: 'Placilla', region: "O'Higgins", codigo: '06308' },
  { nombre: 'Pumanque', region: "O'Higgins", codigo: '06309' },
  { nombre: 'Quinta de Tilcoco', region: "O'Higgins", codigo: '06114' },
  { nombre: 'Rancagua', region: "O'Higgins", codigo: '06101' },
  { nombre: 'Rengo', region: "O'Higgins", codigo: '06115' },
  { nombre: 'Requínoa', region: "O'Higgins", codigo: '06116' },
  { nombre: 'San Fernando', region: "O'Higgins", codigo: '06301' },
  { nombre: 'San Vicente', region: "O'Higgins", codigo: '06117' },
  { nombre: 'Santa Cruz', region: "O'Higgins", codigo: '06310' },
  
  // Región del Maule
  { nombre: 'Cauquenes', region: 'Maule', codigo: '07401' },
  { nombre: 'Chanco', region: 'Maule', codigo: '07402' },
  { nombre: 'Colbún', region: 'Maule', codigo: '07102' },
  { nombre: 'Constitución', region: 'Maule', codigo: '07301' },
  { nombre: 'Curepto', region: 'Maule', codigo: '07302' },
  { nombre: 'Curicó', region: 'Maule', codigo: '07201' },
  { nombre: 'Empedrado', region: 'Maule', codigo: '07303' },
  { nombre: 'Hualañé', region: 'Maule', codigo: '07202' },
  { nombre: 'Licantén', region: 'Maule', codigo: '07203' },
  { nombre: 'Linares', region: 'Maule', codigo: '07103' },
  { nombre: 'Longaví', region: 'Maule', codigo: '07104' },
  { nombre: 'Maule', region: 'Maule', codigo: '07304' },
  { nombre: 'Molina', region: 'Maule', codigo: '07204' },
  { nombre: 'Parral', region: 'Maule', codigo: '07105' },
  { nombre: 'Pelarco', region: 'Maule', codigo: '07305' },
  { nombre: 'Pelluhue', region: 'Maule', codigo: '07403' },
  { nombre: 'Pencahue', region: 'Maule', codigo: '07306' },
  { nombre: 'Rauco', region: 'Maule', codigo: '07205' },
  { nombre: 'Retiro', region: 'Maule', codigo: '07106' },
  { nombre: 'Río Claro', region: 'Maule', codigo: '07307' },
  { nombre: 'Romeral', region: 'Maule', codigo: '07206' },
  { nombre: 'Sagrada Familia', region: 'Maule', codigo: '07207' },
  { nombre: 'San Clemente', region: 'Maule', codigo: '07308' },
  { nombre: 'San Javier', region: 'Maule', codigo: '07107' },
  { nombre: 'San Rafael', region: 'Maule', codigo: '07309' },
  { nombre: 'Talca', region: 'Maule', codigo: '07101' },
  { nombre: 'Teno', region: 'Maule', codigo: '07208' },
  { nombre: 'Vichuquén', region: 'Maule', codigo: '07209' },
  { nombre: 'Villa Alegre', region: 'Maule', codigo: '07108' },
  { nombre: 'Yerbas Buenas', region: 'Maule', codigo: '07109' },
  
  // Región del Ñuble
  { nombre: 'Bulnes', region: 'Ñuble', codigo: '16102' },
  { nombre: 'Chillán', region: 'Ñuble', codigo: '16101' },
  { nombre: 'Chillán Viejo', region: 'Ñuble', codigo: '16103' },
  { nombre: 'Cobquecura', region: 'Ñuble', codigo: '16202' },
  { nombre: 'Coelemu', region: 'Ñuble', codigo: '16203' },
  { nombre: 'Coihueco', region: 'Ñuble', codigo: '16104' },
  { nombre: 'El Carmen', region: 'Ñuble', codigo: '16105' },
  { nombre: 'Ninhue', region: 'Ñuble', codigo: '16204' },
  { nombre: 'Ñiquén', region: 'Ñuble', codigo: '16106' },
  { nombre: 'Pemuco', region: 'Ñuble', codigo: '16107' },
  { nombre: 'Pinto', region: 'Ñuble', codigo: '16108' },
  { nombre: 'Portezuelo', region: 'Ñuble', codigo: '16205' },
  { nombre: 'Quillón', region: 'Ñuble', codigo: '16109' },
  { nombre: 'Quirihue', region: 'Ñuble', codigo: '16206' },
  { nombre: 'Ránquil', region: 'Ñuble', codigo: '16207' },
  { nombre: 'San Carlos', region: 'Ñuble', codigo: '16110' },
  { nombre: 'San Fabián', region: 'Ñuble', codigo: '16111' },
  { nombre: 'San Ignacio', region: 'Ñuble', codigo: '16112' },
  { nombre: 'San Nicolás', region: 'Ñuble', codigo: '16113' },
  { nombre: 'Treguaco', region: 'Ñuble', codigo: '16208' },
  { nombre: 'Yungay', region: 'Ñuble', codigo: '16114' },
  
  // Región del Biobío
  { nombre: 'Alto Biobío', region: 'Biobío', codigo: '08314' },
  { nombre: 'Antuco', region: 'Biobío', codigo: '08302' },
  { nombre: 'Arauco', region: 'Biobío', codigo: '08201' },
  { nombre: 'Cabrero', region: 'Biobío', codigo: '08303' },
  { nombre: 'Cañete', region: 'Biobío', codigo: '08202' },
  { nombre: 'Chiguayante', region: 'Biobío', codigo: '08102' },
  { nombre: 'Concepción', region: 'Biobío', codigo: '08101' },
  { nombre: 'Contulmo', region: 'Biobío', codigo: '08203' },
  { nombre: 'Coronel', region: 'Biobío', codigo: '08103' },
  { nombre: 'Curanilahue', region: 'Biobío', codigo: '08204' },
  { nombre: 'Florida', region: 'Biobío', codigo: '08104' },
  { nombre: 'Hualpén', region: 'Biobío', codigo: '08112' },
  { nombre: 'Hualqui', region: 'Biobío', codigo: '08105' },
  { nombre: 'Laja', region: 'Biobío', codigo: '08304' },
  { nombre: 'Lebu', region: 'Biobío', codigo: '08205' },
  { nombre: 'Los Álamos', region: 'Biobío', codigo: '08206' },
  { nombre: 'Los Ángeles', region: 'Biobío', codigo: '08301' },
  { nombre: 'Lota', region: 'Biobío', codigo: '08106' },
  { nombre: 'Mulchén', region: 'Biobío', codigo: '08305' },
  { nombre: 'Nacimiento', region: 'Biobío', codigo: '08306' },
  { nombre: 'Negrete', region: 'Biobío', codigo: '08307' },
  { nombre: 'Penco', region: 'Biobío', codigo: '08107' },
  { nombre: 'Quilaco', region: 'Biobío', codigo: '08308' },
  { nombre: 'Quilleco', region: 'Biobío', codigo: '08309' },
  { nombre: 'San Pedro de la Paz', region: 'Biobío', codigo: '08108' },
  { nombre: 'San Rosendo', region: 'Biobío', codigo: '08310' },
  { nombre: 'Santa Bárbara', region: 'Biobío', codigo: '08311' },
  { nombre: 'Santa Juana', region: 'Biobío', codigo: '08109' },
  { nombre: 'Talcahuano', region: 'Biobío', codigo: '08110' },
  { nombre: 'Tirúa', region: 'Biobío', codigo: '08207' },
  { nombre: 'Tomé', region: 'Biobío', codigo: '08111' },
  { nombre: 'Tucapel', region: 'Biobío', codigo: '08312' },
  { nombre: 'Yumbel', region: 'Biobío', codigo: '08313' },
  
  // Región de La Araucanía
  { nombre: 'Angol', region: 'La Araucanía', codigo: '09201' },
  { nombre: 'Carahue', region: 'La Araucanía', codigo: '09102' },
  { nombre: 'Cholchol', region: 'La Araucanía', codigo: '09103' },
  { nombre: 'Collipulli', region: 'La Araucanía', codigo: '09202' },
  { nombre: 'Cunco', region: 'La Araucanía', codigo: '09104' },
  { nombre: 'Curacautín', region: 'La Araucanía', codigo: '09203' },
  { nombre: 'Curarrehue', region: 'La Araucanía', codigo: '09105' },
  { nombre: 'Ercilla', region: 'La Araucanía', codigo: '09204' },
  { nombre: 'Freire', region: 'La Araucanía', codigo: '09106' },
  { nombre: 'Galvarino', region: 'La Araucanía', codigo: '09107' },
  { nombre: 'Gorbea', region: 'La Araucanía', codigo: '09108' },
  { nombre: 'Lautaro', region: 'La Araucanía', codigo: '09109' },
  { nombre: 'Loncoche', region: 'La Araucanía', codigo: '09110' },
  { nombre: 'Lonquimay', region: 'La Araucanía', codigo: '09205' },
  { nombre: 'Los Sauces', region: 'La Araucanía', codigo: '09206' },
  { nombre: 'Lumaco', region: 'La Araucanía', codigo: '09207' },
  { nombre: 'Melipeuco', region: 'La Araucanía', codigo: '09111' },
  { nombre: 'Nueva Imperial', region: 'La Araucanía', codigo: '09112' },
  { nombre: 'Padre Las Casas', region: 'La Araucanía', codigo: '09113' },
  { nombre: 'Perquenco', region: 'La Araucanía', codigo: '09114' },
  { nombre: 'Pitrufquén', region: 'La Araucanía', codigo: '09115' },
  { nombre: 'Pucón', region: 'La Araucanía', codigo: '09116' },
  { nombre: 'Purén', region: 'La Araucanía', codigo: '09208' },
  { nombre: 'Renaico', region: 'La Araucanía', codigo: '09209' },
  { nombre: 'Saavedra', region: 'La Araucanía', codigo: '09117' },
  { nombre: 'Temuco', region: 'La Araucanía', codigo: '09101' },
  { nombre: 'Teodoro Schmidt', region: 'La Araucanía', codigo: '09118' },
  { nombre: 'Toltén', region: 'La Araucanía', codigo: '09119' },
  { nombre: 'Traiguén', region: 'La Araucanía', codigo: '09210' },
  { nombre: 'Victoria', region: 'La Araucanía', codigo: '09211' },
  { nombre: 'Vilcún', region: 'La Araucanía', codigo: '09120' },
  { nombre: 'Villarrica', region: 'La Araucanía', codigo: '09121' },
  
  // Región de Los Ríos
  { nombre: 'Corral', region: 'Los Ríos', codigo: '14102' },
  { nombre: 'Futrono', region: 'Los Ríos', codigo: '14201' },
  { nombre: 'La Unión', region: 'Los Ríos', codigo: '14103' },
  { nombre: 'Lago Ranco', region: 'Los Ríos', codigo: '14202' },
  { nombre: 'Lanco', region: 'Los Ríos', codigo: '14104' },
  { nombre: 'Los Lagos', region: 'Los Ríos', codigo: '14203' },
  { nombre: 'Máfil', region: 'Los Ríos', codigo: '14105' },
  { nombre: 'Mariquina', region: 'Los Ríos', codigo: '14106' },
  { nombre: 'Paillaco', region: 'Los Ríos', codigo: '14107' },
  { nombre: 'Panguipulli', region: 'Los Ríos', codigo: '14108' },
  { nombre: 'Río Bueno', region: 'Los Ríos', codigo: '14204' },
  { nombre: 'Valdivia', region: 'Los Ríos', codigo: '14101' },
  
  // Región de Los Lagos
  { nombre: 'Ancud', region: 'Los Lagos', codigo: '10201' },
  { nombre: 'Calbuco', region: 'Los Lagos', codigo: '10102' },
  { nombre: 'Castro', region: 'Los Lagos', codigo: '10202' },
  { nombre: 'Chaitén', region: 'Los Lagos', codigo: '10401' },
  { nombre: 'Chonchi', region: 'Los Lagos', codigo: '10203' },
  { nombre: 'Cochamó', region: 'Los Lagos', codigo: '10103' },
  { nombre: 'Curaco de Vélez', region: 'Los Lagos', codigo: '10204' },
  { nombre: 'Dalcahue', region: 'Los Lagos', codigo: '10205' },
  { nombre: 'Fresia', region: 'Los Lagos', codigo: '10104' },
  { nombre: 'Frutillar', region: 'Los Lagos', codigo: '10105' },
  { nombre: 'Futaleufú', region: 'Los Lagos', codigo: '10402' },
  { nombre: 'Hualaihué', region: 'Los Lagos', codigo: '10403' },
  { nombre: 'Llanquihue', region: 'Los Lagos', codigo: '10107' },
  { nombre: 'Los Muermos', region: 'Los Lagos', codigo: '10108' },
  { nombre: 'Maullín', region: 'Los Lagos', codigo: '10109' },
  { nombre: 'Osorno', region: 'Los Lagos', codigo: '10301' },
  { nombre: 'Palena', region: 'Los Lagos', codigo: '10404' },
  { nombre: 'Puerto Montt', region: 'Los Lagos', codigo: '10101' },
  { nombre: 'Puerto Octay', region: 'Los Lagos', codigo: '10302' },
  { nombre: 'Puerto Varas', region: 'Los Lagos', codigo: '10110' },
  { nombre: 'Puqueldón', region: 'Los Lagos', codigo: '10206' },
  { nombre: 'Purranque', region: 'Los Lagos', codigo: '10303' },
  { nombre: 'Puyehue', region: 'Los Lagos', codigo: '10304' },
  { nombre: 'Queilén', region: 'Los Lagos', codigo: '10207' },
  { nombre: 'Quellón', region: 'Los Lagos', codigo: '10208' },
  { nombre: 'Quemchi', region: 'Los Lagos', codigo: '10209' },
  { nombre: 'Quinchao', region: 'Los Lagos', codigo: '10210' },
  { nombre: 'Río Negro', region: 'Los Lagos', codigo: '10305' },
  { nombre: 'San Juan de la Costa', region: 'Los Lagos', codigo: '10306' },
  { nombre: 'San Pablo', region: 'Los Lagos', codigo: '10307' },
  
  // Región de Aysén
  { nombre: 'Aysén', region: 'Aysén', codigo: '11201' },
  { nombre: 'Chile Chico', region: 'Aysén', codigo: '11301' },
  { nombre: 'Cisnes', region: 'Aysén', codigo: '11202' },
  { nombre: 'Cochrane', region: 'Aysén', codigo: '11401' },
  { nombre: 'Coyhaique', region: 'Aysén', codigo: '11101' },
  { nombre: 'Guaitecas', region: 'Aysén', codigo: '11203' },
  { nombre: 'Lago Verde', region: 'Aysén', codigo: '11102' },
  { nombre: "O'Higgins", region: 'Aysén', codigo: '11402' },
  { nombre: 'Río Ibáñez', region: 'Aysén', codigo: '11302' },
  { nombre: 'Tortel', region: 'Aysén', codigo: '11403' },
  
  // Región de Magallanes
  { nombre: 'Antártica', region: 'Magallanes', codigo: '12201' },
  { nombre: 'Cabo de Hornos', region: 'Magallanes', codigo: '12202' },
  { nombre: 'Laguna Blanca', region: 'Magallanes', codigo: '12102' },
  { nombre: 'Natales', region: 'Magallanes', codigo: '12401' },
  { nombre: 'Porvenir', region: 'Magallanes', codigo: '12301' },
  { nombre: 'Primavera', region: 'Magallanes', codigo: '12302' },
  { nombre: 'Punta Arenas', region: 'Magallanes', codigo: '12101' },
  { nombre: 'Río Verde', region: 'Magallanes', codigo: '12103' },
  { nombre: 'San Gregorio', region: 'Magallanes', codigo: '12104' },
  { nombre: 'Timaukel', region: 'Magallanes', codigo: '12303' },
  { nombre: 'Torres del Paine', region: 'Magallanes', codigo: '12402' }
];

export const getComunasByRegion = (region: string) => {
  return COMUNAS_CHILE.filter(comuna => comuna.region === region);
};

export const searchComunas = (query: string) => {
  if (!query.trim()) return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  return COMUNAS_CHILE.filter(comuna => 
    comuna.nombre.toLowerCase().includes(normalizedQuery)
  ).slice(0, 10); // Limitar a 10 resultados
};

export const getRegiones = () => {
  const regionesSet = new Set(COMUNAS_CHILE.map(comuna => comuna.region));
  const regiones = Array.from(regionesSet);
  return regiones.sort();
};